<?php
/* This file is Copyright AltoLabs 2016. */

$id = Mage::getModel('altolabs_snappic/connect')->getFacebookId(true);
if (empty($id)) { return; }

$session = Mage::getSingleton('core/session');
$product = $session->getCartProductJustAdded();
$session->unsCartProductJustAdded();
?>
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,'script','//connect.facebook.net/en_US/fbevents.js');
fbq('init', '<?php echo($id); ?>');
fbq('track', 'PageView');
<?php if ($product && $product->getId()) { ?>
fbq('track', 'AddToCart', {
  value: '<?php echo($total); ?>',
  currency: '<?php echo($currency); ?>',
  content_type: 'product',
  content_ids: ['snappic_<?php echo($product->getId()); ?>'],
});
<?php } ?>
</script>
<noscript>
  <img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=<?php echo($id); ?>&ev=PageView&noscript=1" />
</noscript>
